### ISSUE TITLE
Implementation Appendix

### ISSUE THREAD

**Issue by Carlycjl** [TerenceCYJ/S2HAND#10]
In the 4.2 Implementation, There is a sentence "We provide more details in the Appendix". But I can't find any Appendix in this paper. Would you please provide the appendix? I would appreciate it so much.

**Comment by TerenceCYJ** [comment]
https://openaccess.thecvf.com/content/CVPR2021/supplemental/Chen_Model-Based_3D_Hand_CVPR_2021_supplemental.pdf
