### ISSUE TITLE
detect.json and detect_all.json

### ISSUE THREAD

**Issue by wjhuang0113** [TerenceCYJ/S2HAND#14]
Hi, 
Excuse me. You use detect.json and detect_all.json in training, 
can you show me how to modify the hand_detect.py to produce the detect.json, thanks.
I means that i can't find where the input and output directory i can modify.
![螢幕擷取畫面 2022-03-09 044642](https://user-images.githubusercontent.com/87569042/157322332-f595c9ae-86ae-4e19-864b-04f829ab5c3f.jpg)

**Comment by TerenceCYJ** [comment]
Hi, you can refer to #2
