### ISSUE TITLE
detect.json file?

### ISSUE THREAD

**Issue by RainCoderJoe** [TerenceCYJ/S2HAND#2]
Hi,
    Excuse me. You use detect.json and detect_all.json in training, are these files created by  examples/openpose_detector/hand_detect.py?

**Comment by TerenceCYJ** [comment]
> Hi,
> Excuse me. You use detect.json and detect_all.json in training, are these files created by examples/openpose_detector/hand_detect.py?

Yes, you can use "hand_detect.py" to create detections and name the file according to your need.

**Comment by RainCoderJoe** [comment]
Thank you for your help!
