### ISSUE TITLE
The Projected 2D Joints seems collaps ?

### ISSUE THREAD

**Issue by tlok666** [TerenceCYJ/S2HAND#4]
Hi, Thank you for sharing this work.

I try to reproduce the training process on FreiHAND dataset. So, I cloned the original code in this repo.

Only changed:
1、the 'model = nn.DataParallel(model.cuda())' in 'train.py' into 'model = model.cuda()', since return a dict with nn.DataParallel returns error.
2、"train_batch":32, into "train_batch":32, in 'SSL-e2e.json'

But, I find the 'Projected 2D Joints 𝑱𝒑𝒓' is collapsing into a point. As the figure2.1 show in the picture below.
![0002_0001700](https://user-images.githubusercontent.com/12291907/130449739-63e187a2-f5d7-493c-a8b1-08abf75be397.png)

Is there anything else I need to pay attention to?

**Comment by TerenceCYJ** [comment]
Hi. The render-related loss may cause the collapse when the pose and texture are not accurate. I would recommend you to try the stage-wise training procedure or use stage-wise training at the start to initialize the end-to-end learning.

**Comment by tlok666** [comment]
> Hi. The render-related loss may cause the collapse when the pose and texture are not accurate. I would recommend you to try the stage-wise training procedure or use stage-wise training at the start to initialize the end-to-end learning.

Thanks. I tried your suggestion and it works. 
By the way. Can I ask, what is the PyTorch version on your computer?(I tried several versions, but none of them support return 'dict' under 'nn.DataParallel' mode)

**Comment by TerenceCYJ** [comment]
The code was developed with PyTorch 1.1.

**Comment by tlok666** [comment]
> The code was developed with PyTorch 1.1.

Thanks for your answers.
