### ISSUE TITLE
FreiHAND pretrained model

### ISSUE THREAD

**Issue by RyosukeHori** [TerenceCYJ/S2HAND#5]
Hi,
Thank you for sharing your interesting work!

I have tried to reproduce the evaluation process on FreiHAND dataset using the pretrained model ([texturehand_freihand.t7](https://www.dropbox.com/s/kh4xxkfm08bh8py/texturehand_freihand.t7?dl=0)).

The output hand models seem to be estimated by the model trained using "Average Pose Prior" rather than your pose prior proposed in the supplementary material, as shown below.

- Example of the output image (0000_0000029.png)
![0000_0000029](https://user-images.githubusercontent.com/62050929/130462188-03e370e4-681c-4048-9522-c85653fe0e18.png)

- Images in the supplementary materials
<img width="653" alt="image from supplimentary material" src="https://user-images.githubusercontent.com/62050929/130462222-dc4f622e-f0a3-43e6-a14c-de2145094102.png">

Is it possible to specify your proposed pose prior as the skeleton regularization when running the evaluation process?
If not, could you please share the model trained with your proposed pose prior?

**Comment by TerenceCYJ** [comment]
Hi, thanks for your interest. The provided example model (which might be the average prior one) is not the final version. To reproduce reconstruction with a better pose prior, you could reimplement the training with prior loss. And yes, using the skeleton regularization term to do fitting-based refinement could also help if you want to get a more reasonable pose.

BTW, the current project is not actively maintained. An extended version might be further presented.
