### ISSUE TITLE
Did the 'Camera Intrinsic Parameter' predicted from networks?

### ISSUE THREAD

**Issue by tlok666** [TerenceCYJ/S2HAND#6]
Hi,
I have a question about the 'Camera Intrinsic Parameter' Ks.
![image](https://user-images.githubusercontent.com/12291907/131800714-4125621b-670f-4320-9ba4-ae61631624b6.png)
In your paper, I think the Camera Intrinsic Parameters were predicted from networks.
And I also found clues in line 210 'https://github.com/TerenceCYJ/S2HAND/blob/main/examples/utils/freihandnet.py'
![image](https://user-images.githubusercontent.com/12291907/131799967-409dbd19-f1ef-406c-a4fd-4b5416b07f36.png)

But when it comes to the loss function. I find you used Camera Intrinsic Parameters 'Ks' from the dataset to project 3D coordinates into 2D.
in line 48 'https://github.com/TerenceCYJ/S2HAND/blob/main/examples/train.py'
![image](https://user-images.githubusercontent.com/12291907/131800448-977b3f66-b026-4cbd-a177-4f78d9b48282.png)

I was confused about the projection function. Why would you use the 'Ks' from the dataset? What is the relationship between those two operations?

Best!

**Comment by TerenceCYJ** [comment]
Hi.

The camera parameters (s, R, T) show the position of the hand mesh in camera coordinates. While the intrinsic parameters include the focal length and the optical center, and the intrinsic is used for projecting 3D coordinates into 2D space.

In our work, we use the intrinsic that is provided along with the input RGB image.

**Comment by tlok666** [comment]
> e camera parameters (s, R, T) shows the position of the hand mesh in camera coordinates. While the intrinsic parameters include the focal length and the optical center, and the intrinsic is used for projecting 3D coordinates into 2D space.

Thanks for your reply. 

To my understanding, your mentioned camera parameters (s, R, T) only include scale and translation shown below:
![image](https://user-images.githubusercontent.com/12291907/132004570-5f34e5d3-b0dd-4a9d-b79f-5130f2e8b0a8.png)

Does it matter whether adopting this scale and translation in camera space?

**Comment by TerenceCYJ** [comment]
When using the camera intrinsic to project 3D joints into 2D and supervise the learning in 2D, I think the scale and translation matter. (Although we evaluate aligned results for FreiHAND and HO3D.) And the rotation is used in `rot_pose_beta_to_mesh`.

BTW, there is another option to get rid of using the camera intrinsic is that use orthogonal projection in [1], but in that case, you don't get the real 3D position in camera space.

[1] Learning Category-Specific Mesh Reconstruction from Image Collections.

**Comment by tlok666** [comment]
It makes sense. Thank you very much！
